# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: video-portal-asset-api-key
spec:
  name: Secret Api Key For VideoPortal
  policies:
    - BucketFullAccess
    - FunctionFullAccess
    - IdentityFullAccess
---
# BUCKET - User
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-video-portal-asset-user-bucket
spec:
  title: User
  description: Video Portal User
  icon: 3d_rotation
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    surname:
      type: string
      title: surname
      description: Description of the surname input
      options:
        position: bottom
    mail:
      type: string
      title: mail
      description: Description of the mail input
      options:
        position: bottom
    profile_picture:
      type: storage
      title: profile_picture
      description: Description of the profile_picture input
      options:
        position: bottom
    eighteen_plus:
      type: boolean
      title: eighteen_plus
      description: Description of the eighteen_plus input
      options:
        position: bottom
      default: false
    saved_movies:
      type: relation
      title: saved_movies
      description: Description of the saved_movies input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: title
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-movies-bucket
    saved_series:
      type: relation
      title: saved_series
      description: Description of the saved_series input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: title
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-series-bucket
    identity:
      type: string
      title: identity
      description: Description of the identity input
      options:
        position: bottom
    liked_series:
      type: relation
      title: liked_series
      description: Description of the liked_series input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-series-bucket
    disliked_series:
      type: relation
      title: disliked_series
      description: Description of the disliked_series input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-series-bucket
    liked_movies:
      type: relation
      title: liked_movies
      description: Description of the liked_movies input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-movies-bucket
    disliked_movies:
      type: relation
      title: disliked_movies
      description: Description of the disliked_movies input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-movies-bucket
  acl:
    write: true==true
    read: true==true
  order: 21
---
# BUCKET - Series
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-video-portal-asset-series-bucket
spec:
  title: Series
  description: Video Portal Series
  icon: 3d_rotation
  primary: title
  readOnly: false
  history: false
  properties:
    title:
      type: string
      title: title
      description: Title of the row
      options:
        position: left
    description:
      type: textarea
      title: description
      description: Description of the row
      options:
        position: right
    country:
      type: string
      title: country
      description: Description of the country input
      options:
        position: bottom
    imdb_score:
      type: string
      title: imdb_score
      description: Description of the imdb_score input
      options:
        position: bottom
    duration:
      type: number
      title: duration
      description: Description of the duration input
      options:
        position: bottom
      minimum: 0
    cover:
      type: storage
      title: cover
      description: Description of the cover input
      options:
        position: bottom
    season:
      type: array
      title: seasons
      description: Description of the season input
      options:
        position: bottom
      items:
        title: Title of the items
        type: object
        properties:
          episodes:
            type: array
            title: episodes
            description: Description of the episodes input
            options:
              position: bottom
            items:
              title: Title of the items
              type: object
              properties:
                title:
                  type: string
                  title: title
                  description: Description of the title input
                  options:
                    position: bottom
                date:
                  type: date
                  title: date
                  description: Description of the date input
                  options:
                    position: bottom
                description:
                  type: textarea
                  title: description
                  description: Description of the description input
                  options:
                    position: bottom
                video:
                  type: storage
                  title: video
                  description: Description of the video input
                  options:
                    position: bottom
                cover:
                  type: storage
                  title: cover
                  description: Description of the cover input
                  options:
                    position: bottom
                duration:
                  type: number
                  title: duration
                  description: Description of the duration input
                  options:
                    position: bottom
                  minimum: 0
    year_of_construction:
      type: string
      title: year_of_construction
      description: Description of the year_of_construction input
      options:
        position: bottom
    eighteen_plus:
      type: boolean
      title: eighteen_plus
      description: Description of the eighteen_plus input
      options:
        position: bottom
      default: false
    genre:
      type: relation
      title: genres
      description: Description of the genre input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-genres-bucket
    actors:
      type: relation
      title: actors
      description: Description of the actors input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-actors-bucket
  acl:
    write: true==true
    read: true==true
  order: 22
---
# BUCKET - Movies
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-video-portal-asset-movies-bucket
spec:
  title: Movies
  description: Video Portal Movies
  icon: 3d_rotation
  primary: title
  readOnly: false
  history: false
  properties:
    title:
      type: string
      title: title
      description: Title of the row
      options:
        position: left
    description:
      type: textarea
      title: description
      description: Description of the row
      options:
        position: right
    cover:
      type: storage
      title: cover
      description: Description of the cover input
      options:
        position: bottom
    movie:
      type: storage
      title: movie
      description: Description of the movie input
      options:
        position: bottom
    country:
      type: string
      title: country
      description: Description of the country input
      options:
        position: bottom
    duration:
      type: number
      title: duration
      description: Description of the duration input
      options:
        position: bottom
      minimum: 0
    imdb_score:
      type: string
      title: imdb_score
      description: Description of the imdb_score input
      options:
        position: bottom
    eighteen_plus:
      type: boolean
      title: eighteen_plus
      description: Description of the eighteen_plus input
      options:
        position: bottom
      default: false
    year_of_construction:
      type: string
      title: year_of_construction
      description: Description of the year_of_construction input
      options:
        position: bottom
    genres:
      type: relation
      title: genres
      description: Description of the genres input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-genres-bucket
    actors:
      type: relation
      title: actors
      description: Description of the actors input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-actors-bucket
  acl:
    write: true==true
    read: true==true
  order: 23
---
# BUCKET - Genres
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-video-portal-asset-genres-bucket
spec:
  title: Genres
  description: Video Portal Genres
  icon: 3d_rotation
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    icon:
      type: string
      title: icon
      description: Description of the icon input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 24
---
# BUCKET - Actors
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-video-portal-asset-actors-bucket
spec:
  title: Actors
  description: Describe your new bucket
  icon: 3d_rotation
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: bottom
    image:
      type: storage
      title: image
      description: Description of the image input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 25
---
# BUCKET - Site Configurations
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-video-portal-asset-site-configurations-bucket
spec:
  title: Site Configurations
  description: Describe your new bucket
  icon: 3d_rotation
  primary: title
  readOnly: false
  history: false
  properties:
    logo:
      type: storage
      title: logo
      description: Description of the logo input
      options:
        position: bottom
    title:
      type: string
      title: title
      description: Description of the title input
      options:
        position: bottom
    home_movies:
      type: relation
      title: home_movies
      description: Description of the home_movies input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-movies-bucket
    home_series:
      type: relation
      title: home_series
      description: Description of the home_series input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-series-bucket
  acl:
    write: true==true
    read: true==true
  order: 26
---
# FUNCTION - Video-Portal Auth
apiVersion: function/v1
kind: Function
metadata:
  name: spica-video-portal-asset-video-portal-auth-function
spec:
  language: javascript
  timeout: 34.7
  environment:
    - name: USER_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-video-portal-asset-user-bucket
    - name: SECRET_API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: video-portal-asset-api-key
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
    - name: "@spica-devkit/identity"
      version: latest
  title: Video-Portal Auth
  code: ./function/spica-video-portal-asset-video-portal-auth-function.js
  runtime:
    name: Node
    language: Javascript
---
# TRIGGER - register
apiVersion: function/v1
kind: Trigger
metadata:
  name: register
spec:
  type: http
  active: true
  name: register
  func: spica-video-portal-asset-video-portal-auth-function
  httpOptions:
    method: Post
    path: /video-register